/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Copyright 2011  Wayne Krug
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  OneWire.cpp obtained from <http://www.pjrc.com/teensy/td_libs_OneWire.html>
 *  and written by Jim Studt and others.  See OneWire.cpp for full copyright
 *  details.
 */
package com.hittindasauce.Dashboard;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author fritz
 */
public class MainDashboard extends javax.swing.JFrame {

    /** Creates new form MainDashboard */
    public MainDashboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        readme_window = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        readme_area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        t1_readout = new javax.swing.JTextField();
        t1_history = new javax.swing.JButton();
        t2_readout = new javax.swing.JTextField();
        t2_history = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t3_readout = new javax.swing.JTextField();
        t3_history = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t4_readout = new javax.swing.JTextField();
        t4_history = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t5_readout = new javax.swing.JTextField();
        t5_history = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t6_readout = new javax.swing.JTextField();
        t6_history = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        t7_readout = new javax.swing.JTextField();
        t7_history = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t8_readout = new javax.swing.JTextField();
        t8_history = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ambient_readout = new javax.swing.JTextField();
        ambient_history = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        polling_rate_setting = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        change_polling_rate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        status_area = new javax.swing.JTextArea();
        man_menu_bar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        save_history_item = new javax.swing.JMenuItem();
        save_status_item = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit_item = new javax.swing.JMenuItem();
        device_menu = new javax.swing.JMenu();
        configure_item = new javax.swing.JMenuItem();
        connect_item = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        readme_item = new javax.swing.JMenuItem();
        about_item = new javax.swing.JMenuItem();

        readme_window.setTitle("README");
        readme_window.setMinimumSize(new java.awt.Dimension(400, 300));

        readme_area.setColumns(20);
        readme_area.setRows(5);
        jScrollPane2.setViewportView(readme_area);

        javax.swing.GroupLayout readme_windowLayout = new javax.swing.GroupLayout(readme_window.getContentPane());
        readme_window.getContentPane().setLayout(readme_windowLayout);
        readme_windowLayout.setHorizontalGroup(
            readme_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readme_windowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        readme_windowLayout.setVerticalGroup(
            readme_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readme_windowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BBQ Thermocouple Dashboard");
        setName("mainWindow"); // NOI18N
        setResizable(false);

        jLabel1.setText("Thermocouple 1");

        t1_readout.setEditable(false);
        t1_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t1_readout.setText("0.000");
        t1_readout.setToolTipText("Readout for thermocouple 1");
        t1_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1_readoutActionPerformed(evt);
            }
        });

        t1_history.setText("History");
        t1_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1_historyActionPerformed(evt);
            }
        });

        t2_readout.setEditable(false);
        t2_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t2_readout.setText("0.000");
        t2_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2_readoutActionPerformed(evt);
            }
        });

        t2_history.setText("History");
        t2_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2_historyActionPerformed(evt);
            }
        });

        jLabel2.setText("Thermocouple 2");

        t3_readout.setEditable(false);
        t3_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t3_readout.setText("0.000");
        t3_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3_readoutActionPerformed(evt);
            }
        });

        t3_history.setText("History");
        t3_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3_historyActionPerformed(evt);
            }
        });

        jLabel3.setText("Thermocouple 3");

        t4_readout.setEditable(false);
        t4_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t4_readout.setText("0.000");
        t4_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4_readoutActionPerformed(evt);
            }
        });

        t4_history.setText("History");
        t4_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4_historyActionPerformed(evt);
            }
        });

        jLabel4.setText("Thermocouple 4");

        t5_readout.setEditable(false);
        t5_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t5_readout.setText("0.000");
        t5_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5_readoutActionPerformed(evt);
            }
        });

        t5_history.setText("History");
        t5_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5_historyActionPerformed(evt);
            }
        });

        jLabel5.setText("Thermocouple 5");

        t6_readout.setEditable(false);
        t6_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t6_readout.setText("0.000");
        t6_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6_readoutActionPerformed(evt);
            }
        });

        t6_history.setText("History");
        t6_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6_historyActionPerformed(evt);
            }
        });

        jLabel6.setText("Thermocouple 6");

        t7_readout.setEditable(false);
        t7_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t7_readout.setText("0.000");
        t7_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7_readoutActionPerformed(evt);
            }
        });

        t7_history.setText("History");
        t7_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7_historyActionPerformed(evt);
            }
        });

        jLabel7.setText("Thermocouple 7");

        t8_readout.setEditable(false);
        t8_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t8_readout.setText("0.000");
        t8_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8_readoutActionPerformed(evt);
            }
        });

        t8_history.setText("History");
        t8_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8_historyActionPerformed(evt);
            }
        });

        jLabel8.setText("Thermocouple 8");

        ambient_readout.setEditable(false);
        ambient_readout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ambient_readout.setText("0.000");
        ambient_readout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambient_readoutActionPerformed(evt);
            }
        });

        ambient_history.setText("History");
        ambient_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambient_historyActionPerformed(evt);
            }
        });

        jLabel9.setText("Ambient");

        jLabel10.setText("Polling rate");

        jLabel11.setText("second(s)");

        change_polling_rate.setText("Change");
        change_polling_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_polling_rateActionPerformed(evt);
            }
        });

        status_area.setColumns(20);
        status_area.setEditable(false);
        status_area.setRows(5);
        jScrollPane1.setViewportView(status_area);

        file_menu.setText("File");

        save_history_item.setText("Save history");
        save_history_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_history_itemActionPerformed(evt);
            }
        });
        file_menu.add(save_history_item);

        save_status_item.setText("Save status log");
        save_status_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_status_itemActionPerformed(evt);
            }
        });
        file_menu.add(save_status_item);
        file_menu.add(jSeparator1);

        exit_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_itemActionPerformed(evt);
            }
        });
        file_menu.add(exit_item);

        man_menu_bar.add(file_menu);

        device_menu.setText("Device");

        configure_item.setText("Configure");
        configure_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configure_itemActionPerformed(evt);
            }
        });
        device_menu.add(configure_item);

        connect_item.setText("Connect");
        connect_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_itemActionPerformed(evt);
            }
        });
        device_menu.add(connect_item);

        man_menu_bar.add(device_menu);

        help_menu.setText("Help");

        readme_item.setText("Readme");
        readme_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readme_itemActionPerformed(evt);
            }
        });
        help_menu.add(readme_item);

        about_item.setText("About");
        about_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_itemActionPerformed(evt);
            }
        });
        help_menu.add(about_item);

        man_menu_bar.add(help_menu);

        setJMenuBar(man_menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ambient_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(ambient_history))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t1_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t1_history))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t2_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t2_history))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3_history))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t4_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t4_history))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t5_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t5_history))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t6_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t6_history))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t7_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t7_history))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t8_readout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t8_history))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polling_rate_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(change_polling_rate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t1_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t2_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t3_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t4_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t5_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t6_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t7_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t8_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8_history))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ambient_history)
                    .addComponent(ambient_readout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(polling_rate_setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(change_polling_rate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1_readoutActionPerformed

    private void t1_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1_historyActionPerformed

    private void t2_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2_readoutActionPerformed

    private void t2_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2_historyActionPerformed

    private void t3_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3_readoutActionPerformed

    private void t3_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3_historyActionPerformed

    private void t4_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4_readoutActionPerformed

    private void t4_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4_historyActionPerformed

    private void t5_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5_readoutActionPerformed

    private void t5_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5_historyActionPerformed

    private void t6_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6_readoutActionPerformed

    private void t6_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6_historyActionPerformed

    private void t7_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7_readoutActionPerformed

    private void t7_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7_historyActionPerformed

    private void t8_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8_readoutActionPerformed

    private void t8_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8_historyActionPerformed

    private void ambient_readoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambient_readoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ambient_readoutActionPerformed

    private void ambient_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambient_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ambient_historyActionPerformed

    private void change_polling_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_polling_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_change_polling_rateActionPerformed

    private void exit_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_itemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_itemActionPerformed

    private void about_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_itemActionPerformed
        JOptionPane.showMessageDialog(this, "Test");
    }//GEN-LAST:event_about_itemActionPerformed

    private void save_history_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_history_itemActionPerformed
        int return_val = jFileChooser1.showSaveDialog(this);

        // Do the save stuff here

        if (return_val == jFileChooser1.APPROVE_OPTION) {
            status_area.append("Saved history\n");
        }
    }//GEN-LAST:event_save_history_itemActionPerformed

    private void save_status_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_status_itemActionPerformed
        int return_val = jFileChooser1.showSaveDialog(this);

        // Do the save stuff here

        if (return_val == jFileChooser1.APPROVE_OPTION) {
            status_area.append("Saved status log\n");
        }
    }//GEN-LAST:event_save_status_itemActionPerformed

    private void configure_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configure_itemActionPerformed
        status_area.append("Arduino interface configured\n");
    }//GEN-LAST:event_configure_itemActionPerformed

    private void connect_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_itemActionPerformed
        status_area.append("Successfully connected to Arduino\n");
    }//GEN-LAST:event_connect_itemActionPerformed

    private void readme_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readme_itemActionPerformed
        readme_window.setVisible(true);
    }//GEN-LAST:event_readme_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                // Use the system native look and feel
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainDashboard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainDashboard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainDashboard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MainDashboard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_item;
    private javax.swing.JButton ambient_history;
    private javax.swing.JTextField ambient_readout;
    private javax.swing.JButton change_polling_rate;
    private javax.swing.JMenuItem configure_item;
    private javax.swing.JMenuItem connect_item;
    private javax.swing.JMenu device_menu;
    private javax.swing.JMenuItem exit_item;
    private javax.swing.JMenu file_menu;
    private javax.swing.JMenu help_menu;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuBar man_menu_bar;
    private javax.swing.JSpinner polling_rate_setting;
    private javax.swing.JTextArea readme_area;
    private javax.swing.JMenuItem readme_item;
    private javax.swing.JFrame readme_window;
    private javax.swing.JMenuItem save_history_item;
    private javax.swing.JMenuItem save_status_item;
    private javax.swing.JTextArea status_area;
    private javax.swing.JButton t1_history;
    private javax.swing.JTextField t1_readout;
    private javax.swing.JButton t2_history;
    private javax.swing.JTextField t2_readout;
    private javax.swing.JButton t3_history;
    private javax.swing.JTextField t3_readout;
    private javax.swing.JButton t4_history;
    private javax.swing.JTextField t4_readout;
    private javax.swing.JButton t5_history;
    private javax.swing.JTextField t5_readout;
    private javax.swing.JButton t6_history;
    private javax.swing.JTextField t6_readout;
    private javax.swing.JButton t7_history;
    private javax.swing.JTextField t7_readout;
    private javax.swing.JButton t8_history;
    private javax.swing.JTextField t8_readout;
    // End of variables declaration//GEN-END:variables
}
